### ISSUE TITLE
AVX-512: ERROR: no suitable kernels found.

### ISSUE THREAD

**Issue by jeffhammond** [HPAC/TTC#3]
``` sh
[jrhammo@bowman-lsm1 github]$ ttc --perm=1,0,2 --size=1000,768,16 --dataType=d --alpha=1.0 --beta=1.0 --numThreads=120 --architecture=avx512
WARNING: you did not specify an thread affinity. We are using: compact,1 by default
[generate] Generate all versions
ERROR: no suitable kernels found.
```

AVX works.  Not sure if lack of support for AVX-512 is intentional.

**Comment by springer13** [comment]
Yes, so far I have just added a micro-kernel for single precision. I was planing to add the kernels for all other datatypes once I have access to an AVX512 architecture. That being said, I could code them up earlier if you need them.

**Comment by jeffhammond** [comment]
Ah, that makes sense.  It's not a big deal for me right now.

**Comment by springer13** [comment]
I have added some checks to make the user aware of the current limitations. FYI, KNC is currently also limited to single-precision.
