### ISSUE TITLE
/proc/cpuinfo does not exist on Mac

### ISSUE THREAD

**Issue by jeffhammond** [HPAC/TTC#6]
I saw an error because of this:

```
jrhammon-mac01:TTC-github jrhammon$ git grep cpuinfo
ttc/ttc_util.py:        f = open("/proc/cpuinfo", "r")
```

Mac should be a second-class citizen for this project, so I don't know that you should fix this in a nontrivial way.  However, if you want to solve it, http://osxdaily.com/2011/07/15/get-cpu-info-via-command-line-in-mac-os-x/ has a few different command line alternatives.

**Comment by springer13** [comment]
Thanks for pointing this out. You are absolutely right. I've developed this project on linux and I have not tested TTC on macOS. Is Mac important to you?

**Comment by jeffhammond** [comment]
Mac is my primary development platform but performance is not critical.  I would be happy for things to work but lack all the features of the Linux version, if that makes it easier.

**Comment by springer13** [comment]
okay, please pull and see if this fixes all issues with OS X.

**Comment by springer13** [comment]
I'm closing this ticket. I've tested TTC on one of our Macs and it is working now.
